# ✅ Step: Trigger Render Deployment
# This step triggers a manual deployment on Render using the deploy hook URL
# Only runs if the code was pushed to the 'develop' branch
name: Deploy to Render (Production)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Render Production Deploy
        # 🛠 Set environment variable for the deploy hook URL (from GitHub Secrets)
        env:
          DEPLOY_URL: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
        # 🚀 Send a request to trigger the deployment via Render's Deploy Hook
        run: |
          curl "$DEPLOY_URL"