# Name of the workflow shown in GitHub Actions UI
name: Run Cypress Tests

# Trigger this workflow when a Pull Request is opened to the develop branch
on:
  pull_request:
    branches:
      - develop

jobs:
  # Define a job called "test"
  test:
    # This job will run on the latest Ubuntu runner provided by GitHub
    runs-on: ubuntu-latest

    # Test the app across multiple Node.js versions (for compatibility)
    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
      # Step 1: Checkout the code from the pull request branch
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up the specified Node.js version for this job
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      # Step 3: Install all project dependencies (from package.json)
      - name: Install dependencies
        run: npm install

      # Step 4: Start the server in the background, then wait for it to be accessible
      - name: Start the server in background
        run: |
          npm run develop &                     # Start the app in the background
          npx wait-on http://localhost:3001  # Wait until the server is ready

      # Step 5: Run all Cypress tests
      - name: Run Cypress tests
        run: npx cypress run
